language: cpp
before_install:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-none-eabi
env:
  matrix:
    - TARGET=stm32f4discovery/skel
    - TARGET=stm32f429discovery/leds
    - TARGET=mbed-lpc1768/leds
script:
  - make -C examples/$TARGET
notifications:
  email: false
